# NOTE: update this with your service name
service: meta-app-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: leaderboards

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in add-user.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  add-user:
    handler: add-user.main
    events:
      - http:
          path: leaderboards
          method: post
          cors: true
          authorizer: aws_iam
  get-user:
    # Defines an HTTP API endpoint that calls the main function in get-user.js
    # - path: url path is /leaderboards/{id}
    # - method: GET request
    handler: get-user.main
    events:
      - http:
          path: leaderboards/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list-users:
    # Defines an HTTP API endpoint that calls the main function in list-users.js
    # - path: url path is /leaderboards
    # - method: GET request
    handler: list-users.main
    events:
      - http:
          path: leaderboards
          method: get
          cors: true
          authorizer: aws_iam
  update-points:
    # Defines an HTTP API endpoint that calls the main function in update-points.js
    # - path: url path is /leaderboards/{id}
    # - method: PUT request
    handler: update-points.main
    events:
      - http:
          path: leaderboards/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete-user:
    # Defines an HTTP API endpoint that calls the main function in delete-user.js
    # - path: url path is /leaderboards/{id}
    # - method: DELETE request
    handler: delete-user.main
    events:
      - http:
          path: leaderboards/{id}
          method: delete
          cors: true
          authorizer: aws_iam
# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}